language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_script:
  - curl --version
  - composer self-update
  - composer install
  - ~/.nvm/nvm.sh install v0.6.14
  - ~/.nvm/nvm.sh run v0.6.14
  - mkdir -p build/logs
script: make test
after_success:
  - travis_retry php vendor/bin/coveralls
